config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  resources :admins
  resources :transactions
  root 'home#index'
  
  get 'passenger_search', to: 'passengers#passenger_search', as: 'passenger_search'
  get 'ticket_book', to: 'tickets#ticket_book', as: 'ticket_book'
  post 'ticket_book_create', to: 'tickets#ticket_book_create', as:'ticket_book_create'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'passengers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'delete_passenger/:id', to: 'passengers#destroy', as: 'delete_passenger'
  get 'delete_admin/:id', to: 'admins#destroy', as: 'delete_admin'
  resources :admin_sessions, only: [:new, :create, :destroy]
  get 'admin_login', to: 'admin_sessions#new', as: 'admin_login'
  get 'admin_logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
    has_many :tickets, dependent: :destroy
    has_many :reviews, dependent: :destroy
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]

  # GET /trains or /trains.json
  def index
    
    
    if !admin_user
      current_time = Time.now
      @trains = Train.where('departure_date > ?', current_time)
    else
      @trains = Train.all
    end

    # Apply additional search filters here...
    if params[:search_departure_station].present? && params[:search_termination_station].present?
      @trains = @trains.where('departure_station = ? AND termination_station = ?', params[:search_departure_station], params[:search_termination_station])
    elsif params[:search_departure_station].present?
      @trains = @trains.where(departure_station: params[:search_departure_station])
    elsif params[:search_termination_station].present?
      @trains = @trains.where(termination_station: params[:search_termination_station])
    elsif params[:search_average_rating].present?
      @trains = @trains.where('average_rating > ?', params[:search_average_rating])
    end
  end

  # GET /trains/1 or /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)
    @train.average_rating=0
    respond_to do |format|
      if @train.seats_left > @train.train_capacity || @train.departure_date > @train.arrival_date
        format.html { redirect_to trains_url, notice: "Check Train parameters" }
      elsif @train.seats_left <= @train.train_capacity && @train.save
        format.html { redirect_to train_url(@train), notice: "Train was successfully created." }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      @train.average_rating=0
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:train_number, :departure_station, :termination_station, :departure_date, :departure_time, :arrival_date, :arrival_time, :ticket_price, :train_capacity, :seats_left)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :train_number %>
    <%= form.number_field :train_number %>
  </div>

  <div class="field">
    <%= form.label :departure_station %>
    <%= form.text_field :departure_station %>
  </div>

  <div class="field">
    <%= form.label :termination_station %>
    <%= form.text_field :termination_station %>
  </div>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :departure_time %>
    <%= form.time_select :departure_time %>
  </div>

  <div class="field">
    <%= form.label :arrival_date %>
    <%= form.date_select :arrival_date %>
  </div>

  <div class="field">
    <%= form.label :arrival_time %>
    <%= form.time_select :arrival_time %>
  </div>

  <div class="field">
    <%= form.label :ticket_price %>
    <%= form.number_field :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :train_capacity %>
    <%= form.number_field :train_capacity %>
  </div>

  <div class="field">
    <%= form.label :seats_left %>
    <%= form.number_field :seats_left %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>


<%= form_tag trains_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search_departure_station, params[:search_departure_station], placeholder: "Enter Departure Station" %>
    <%= text_field_tag :search_termination_station, params[:search_termination_station], placeholder: "Enter Termination Station" %>
    <%= submit_tag "search", :departure_station => nil, :termination_station => nil %>
  </p>
<% end %>

<%= form_tag trains_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search_average_rating, params[:search_average_rating], placeholder: "Enter average rating"%>
    <%= submit_tag "search", :average_rating => nil%>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Train number</th>
      <th>Departure station</th>
      <th>Termination station</th>
      <th>Departure date</th>
      <th>Departure time</th>
      <th>Arrival date</th>
      <th>Arrival time</th>
      <th>Ticket price</th>
      <th>Train capacity</th>
      <th>Seats left</th>
      <th>Average Rating </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.train_number %></td>
        <td><%= train.departure_station %></td>
        <td><%= train.termination_station %></td>
        <td><%= train.departure_date %></td>
        <td><%= train.departure_time.strftime("%I:%M %p")%></td>
        <td><%= train.arrival_date %></td>
        <td><%= train.arrival_time.strftime("%I:%M %p") %></td>
        <td><%= train.ticket_price %></td>
        <td><%= train.train_capacity %></td>
        <td><%= train.seats_left %></td>
        <td><%= train.average_rating %></td>
        <% if admin_user %>
        <td>  <%= link_to 'Add review', new_review_path(:train_id => train.id) %></td>
        <% end %>
        <td><%= link_to 'Show Reviews', reviews_path(:train_id => train.id) %></td>
        <td><%= link_to 'Book', new_ticket_path(:train_id => train.id) %></td>
        <% if !admin_user %>
          <td><%= link_to 'Book for somebody?', ticket_book_path(:train_id => train.id) %></td>
        <% end %>
        <% if admin_user %>
          <td><%= link_to 'Show', train %></td>
          <td><%= link_to 'Edit', edit_train_path(train) %></td>
          <td><%= button_to 'Delete', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_user %>
  <%= link_to 'New Train', new_train_path %>
<% end %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Train number:</strong>
  <%= @train.train_number %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @train.departure_station %>
</p>

<p>
  <strong>Termination station:</strong>
  <%= @train.termination_station %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @train.departure_date %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @train.departure_time %>
</p>

<p>
  <strong>Arrival date:</strong>
  <%= @train.arrival_date %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @train.arrival_time %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @train.ticket_price %>
</p>

<p>
  <strong>Train capacity:</strong>
  <%= @train.train_capacity %>
</p>

<p>
  <strong>Seats left:</strong>
  <%= @train.seats_left %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>