config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  resources :admins
  resources :transactions
  root 'home#index'
  
  get 'passenger_search', to: 'passengers#passenger_search', as: 'passenger_search'
  get 'ticket_book', to: 'tickets#ticket_book', as: 'ticket_book'
  post 'ticket_book_create', to: 'tickets#ticket_book_create', as:'ticket_book_create'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'passengers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'delete_passenger/:id', to: 'passengers#destroy', as: 'delete_passenger'
  get 'delete_admin/:id', to: 'admins#destroy', as: 'delete_admin'
  resources :admin_sessions, only: [:new, :create, :destroy]
  get 'admin_login', to: 'admin_sessions#new', as: 'admin_login'
  get 'admin_logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authorized, only: [:index]
    def index
    end
  end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_passenger %>
  <h2>Logged in as <%= current_passenger.name %></h2>
  <a><%= link_to "Log Out", logout_path %></a><br>
  <nav>
    <ul>
      <li><%= link_to "My Profile", passenger_path(current_passenger.id) %> </li>
      <li><%= link_to "All Trains", trains_path %> </li>
      <li><%= link_to "Trip History", tickets_path(:passenger_id => current_passenger.id) %> </li>
      <li><%= link_to "All Reviews", reviews_path %> </li>
      <li><%= link_to "My Reviews", reviews_path(:passenger_id => current_passenger.id) %> </li>

    </ul>
  </nav>

  <% elsif admin_user%>
  <h2>Logged in as Admin</h2>
  <a><%= link_to "Log Out", admin_logout_path %></a><br>
  <nav>
    <ul>
      <li><%= link_to "My Profile", admin_path(admin_user.id) %></li>
      <li><%= link_to "All Trains", trains_path %></li>
      <li><%= link_to "All Passengers", passengers_path %></li>
      <li><%= link_to "All Reviews", reviews_path %></li>
      <li><%= link_to "Search for passengers", passenger_search_path %></li>
      <li><%= link_to "All Tickets Booked", tickets_path %></li>
      <li><%= link_to "Log Out", admin_logout_path %></li>
    </ul>
  </nav>
<% else %>
  <nav>
    <ul>
      <li><%= link_to "Sign Up", signup_path %> </li>
      <li><%= link_to "Log In", login_path %></li>
      <li><%= link_to "Login as Admin", admin_login_path %> </li>
    </ul>
  </nav>
  <% end %>