config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  resources :admins
  resources :transactions
  root 'home#index'
  
  get 'passenger_search', to: 'passengers#passenger_search', as: 'passenger_search'
  get 'ticket_book', to: 'tickets#ticket_book', as: 'ticket_book'
  post 'ticket_book_create', to: 'tickets#ticket_book_create', as:'ticket_book_create'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'passengers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'delete_passenger/:id', to: 'passengers#destroy', as: 'delete_passenger'
  get 'delete_admin/:id', to: 'admins#destroy', as: 'delete_admin'
  resources :admin_sessions, only: [:new, :create, :destroy]
  get 'admin_login', to: 'admin_sessions#new', as: 'admin_login'
  get 'admin_logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    # before_create :generate_confirmation_number
    belongs_to :passenger
    belongs_to :train

    # def generate_confirmation_number
    #     # Generate a random confirmation number using SecureRandom
    #     self.confirmation_number = SecureRandom.hex(4).upcase
    #   end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  

  # GET /tickets or /tickets.json
  def index
    if !admin_user
      @tickets = Ticket.where(passenger_id: current_passenger.id)
    elsif params[:search_by_train_number].present?
      @tickets=Ticket.joins(:train).select('tickets.*').group('tickets.id').having('train_number = ?',params[:search_by_train_number])
    else
      @tickets = Ticket.all
    end
  end
  # GET /tickets/1 or /tickets/1.json
  def show
    @train = Train.find_by(id: @ticket.train_id) 
  end

  # GET /tickets/new

  def ticket_book
    @ticket = Ticket.new
    @train = Train.find_by(id: params[:train_id])
    @passengers = Passenger.where(is_admin: false)
  end

  def new
    @ticket = Ticket.new
    if admin_user
      @passengers = Passenger.where(is_admin: false)
    end
    if @train.nil?
      begin
        @train = Train.where(id: params[:train_id])[0]
      rescue
        redirect_to trains_path
      end
    end
  end

  # GET /tickets/1/edit
  def edit
    @train = Train.find_by(id: @ticket.train_id) 
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new
    @train = Train.find_by(id: params[:ticket]["train_id"])
    @ticket.confirmation_number = generate_confirmation_number
    if !admin_user
      @ticket.username = Passenger.find_by(id: current_passenger.id).name
    else
      @ticket.username = Passenger.find_by(id: params[:ticket]["passenger_id"]).name
    end
    if current_passenger
      @ticket.passenger_id = current_passenger.id
      @ticket.train_id = @train.id
    elsif admin_user
      @ticket.passenger_id = params[:ticket]["passenger_id"]
      @ticket.train_id = @train.id
    end

    seats = @train.seats_left-1

    respond_to do |format|
      if Time.now() < @train.departure_date && seats>0 && @ticket.save
        @train.seats_left = @train.seats_left - 1
        @train.save
        format.html{ redirect_to tickets_url(@ticket), notice: "Ticket booked successfully. Confirmation number: #{@ticket.confirmation_number}" }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { redirect_to trains_path, notice: "Can't book this train"}
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def ticket_book_create
    @ticket1 = Ticket.new
    @ticket2 = Ticket.new
    @train = Train.find_by(id: params[:ticket]["train_id"])
    confirmation_number = generate_confirmation_number
    @ticket1.confirmation_number = confirmation_number


    @ticket2.confirmation_number = confirmation_number

    
    @ticket1.passenger_id = current_passenger.id
    @ticket2.passenger_id = params[:ticket]["passenger_id"]
    @ticket1.train_id = @train.id
    @ticket2.train_id = @train.id
    @ticket1.username = Passenger.find_by(id: params[:ticket]["passenger_id"]).name
    @ticket2.username = Passenger.find_by(id: params[:ticket]["passenger_id"]).name

    seats = @train.seats_left-1

    respond_to do |format|
      if seats>0 && @ticket1.save && @ticket2.save
        @train.seats_left = @train.seats_left - 1
        @train.save
        format.html{ redirect_to tickets_url(@ticket1), notice: "Ticket booked successfully. Confirmation number: #{@ticket1.confirmation_number}" }
        format.json { render :show, status: :created, location: @ticket1 }
      else
        format.html { redirect_to trains_path, notice: "No seats left"}
        format.json { render json: @ticket1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update  
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @train = Train.find_by(id: @ticket.train_id)
    
    respond_to do |format|
      if @ticket.delete 
        @train.seats_left = @train.seats_left + 1
        @train.save
        format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
     def ticket_params
       params.require(:ticket).permit(:passenger_id,:credit_number,:ticket_price,:address,:phone_number,:train_id)
     end

    #Generate the confirmation number using SecureRandom
    def generate_confirmation_number
      SecureRandom.random_number(900_000) + 100_000
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>You are purchasing one ticket for the train: <%= @train.train_number %></p>
  
  <div class="field">
    <%= form.label :credit_number, "Credit Card Number" %>
    <% if admin_user %>
      <%= form.text_field :credit_number, :id => 'credit_number',value: admin_user.credit_number %>
    <% else %>
      <%= form.text_field :credit_number, :id => 'credit_number',value: current_passenger.credit_number %>
    <% end %>
    
  </div>

  <div class="field">
    <%= form.label :ticket_price %>
    <%= form.text_field :ticket_price, :id => 'ticket_price', :readonly => true, value: @train.ticket_price %>
  </div>

  <div class="field">
    <%= form.label :address, "Address" %>
    <% if admin_user %>
      <%= form.text_field :address, :id => 'address', value: admin_user.address  %>
    <% else %>
      <%= form.text_field :address, :id => 'address', value: current_passenger.address  %>
    <% end %>
    
  </div>

  <div class="field">
    <%= form.label :phone_number, "Phone Number" %>
    <% if admin_user %>
      <%= form.text_field :phone_number, :id => 'phone_number', value: admin_user.phone_number %>
    <% else %>
      <%= form.text_field :phone_number, :id => 'phone_number', value: current_passenger.phone_number %>
    <% end %>
  </div>
 

  <% if admin_user %>
    <div class="field">
      <%= form.label :passenger_id %>
      <%= form.select :passenger_id, @passengers.map { |passenger| [passenger.name, passenger.id] }, { include_blank: "Select a passenger" } %>
  </div>

  <% end %>

  <div class="field">
    <%= form.hidden_field :train_id, value: @train.id %>
  </div>


  <div class="actions">
    <%= form.submit "Book Ticket"%>
  </div>
<% end %>

app/views/tickets/_form2.html.erb
<%= form_with(model: ticket, url: ticket_book_create_path(@ticket)) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
  
        <ul>
          <% ticket.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>You are purchasing one ticket for the train: <%= @train.train_number %></p>
    
    <div class="field">
      <%= form.label :credit_number, "Credit Card Number" %>
      <% if admin_user %>
        <%= form.text_field :credit_number, :id => 'credit_number',value: admin_user.credit_number %>
      <% else %>
        <%= form.text_field :credit_number, :id => 'credit_number',value: current_passenger.credit_number %>
      <% end %>
      
    </div>
  
    <div class="field">
      <%= form.label :ticket_price %>
      <%= form.text_field :ticket_price, :id => 'ticket_price', :readonly => true, value: @train.ticket_price %>
    </div>
  
    <div class="field">
      <%= form.label :address, "Address" %>
      <% if admin_user %>
        <%= form.text_field :address, :id => 'address', value: admin_user.address  %>
      <% else %>
        <%= form.text_field :address, :id => 'address', value: current_passenger.address  %>
      <% end %>
      
    </div>
  
    <div class="field">
      <%= form.label :phone_number, "Phone Number" %>
      <% if admin_user %>
        <%= form.text_field :phone_number, :id => 'phone_number', value: admin_user.phone_number %>
      <% else %>
        <%= form.text_field :phone_number, :id => 'phone_number', value: current_passenger.phone_number %>
      <% end %>
    </div>
   
  

    <div class="field">
        <%= form.label :passenger_id %>
        <%= form.select :passenger_id, @passengers.map { |passenger| [passenger.name, passenger.id] }, { include_blank: "Select a passenger" } %>
    </div>
  

  
    <div class="field">
      <%= form.hidden_field :train_id, value: @train.id %>
    </div>
  
  
    <div class="actions">
      <%= form.submit "Book Ticket"%>
    </div>
  <% end %>
  

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<% if !admin_user %>
<h1>Trip History</h1>
<%elsif%>
<h1>Tickets</h1>
<% end %>

<% if admin_user %>
  <%= form_tag tickets_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_by_train_number, params[:search_by_train_number], placeholder: "Enter train number" %>
      <%= submit_tag "search"%>
    </p>
  <% end %>
<% end %>



<table>
  <thead>
    <tr>
    
    <th>Train number</th>
      <th>Departure station</th>
      <th>Termination station</th>
      <th>Departure date</th>
      <th>Departure time</th>
      <th>Arrival date</th>
      <th>Arrival time</th>
      <th>Average Rating</th>
    <th> Passenger Name </th>
      <th>Confirmation number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
      
      <td><%= Train.find_by(id: ticket.train_id).train_number %></td>
      
        <td><%= Train.find_by(id: ticket.train_id).departure_station %></td>
        <td><%= Train.find_by(id: ticket.train_id).termination_station %></td>
        <td><%= Train.find_by(id: ticket.train_id).departure_date %></td>
        <td><%= Train.find_by(id: ticket.train_id).departure_time.strftime("%I:%M %p") %></td>
        <td><%= Train.find_by(id: ticket.train_id).arrival_date %></td>
        <td><%= Train.find_by(id: ticket.train_id).arrival_time.strftime("%I:%M %p") %></td>
        <td><%= Train.find_by(id: ticket.train_id).average_rating %></td>
        <td><%= ticket.username %></td>
        <td><%= ticket.confirmation_number %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Add Review', new_review_path(:train_id => ticket.train_id) %></td>
        <td><%= link_to 'Show Reviews', reviews_path(:train_id => ticket.train_id) %></td>
        <td><%= button_to 'Delete', ticket, method: :delete, data:{ confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All trains', trains_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<p>
  <strong>Train number:</strong>
  <%= @train.train_number %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @train.departure_station %>
</p>

<p>
  <strong>Termination station:</strong>
  <%= @train.termination_station %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @train.departure_date %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @train.departure_time %>
</p>

<p>
  <strong>Arrival date:</strong>
  <%= @train.arrival_date %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @train.arrival_time %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @train.ticket_price %>
</p>

<p>
  <strong>Train capacity:</strong>
  <%= @train.train_capacity %>
</p>

<p>
  <strong>Seats left:</strong>
  <%= @train.seats_left %>
</p>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', trains_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Confirmation number:</strong>
  <%= @ticket.confirmation_number %>
</p>

<p>
  <strong>Train number:</strong>
  <%= @train.train_number %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @train.departure_station %>
</p>

<p>
  <strong>Termination station:</strong>
  <%= @train.termination_station %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @train.departure_date %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @train.departure_time %>
</p>

<p>
  <strong>Arrival date:</strong>
  <%= @train.arrival_date %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @train.arrival_time %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @train.ticket_price %>
</p>



<%= link_to 'Back', tickets_path %>

app/views/tickets/ticket_book.html.erb
<h1>New Ticket</h1>

<p>
  <strong>Train number:</strong>
  <%= @train.train_number %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @train.departure_station %>
</p>

<p>
  <strong>Termination station:</strong>
  <%= @train.termination_station %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @train.departure_date %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @train.departure_time %>
</p>

<p>
  <strong>Arrival date:</strong>
  <%= @train.arrival_date %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @train.arrival_time %>
</p>

<p>
  <strong>Ticket price:</strong>
  <%= @train.ticket_price %>
</p>

<p>
  <strong>Train capacity:</strong>
  <%= @train.train_capacity %>
</p>

<p>
  <strong>Seats left:</strong>
  <%= @train.seats_left %>
</p>

<%= render 'form2', ticket: @ticket %>

<%= link_to 'Back', trains_path %>