config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :tickets
  resources :reviews
  resources :passengers
  resources :admins
  resources :transactions
  root 'home#index'
  
  get 'passenger_search', to: 'passengers#passenger_search', as: 'passenger_search'
  get 'ticket_book', to: 'tickets#ticket_book', as: 'ticket_book'
  post 'ticket_book_create', to: 'tickets#ticket_book_create', as:'ticket_book_create'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'passengers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'delete_passenger/:id', to: 'passengers#destroy', as: 'delete_passenger'
  get 'delete_admin/:id', to: 'admins#destroy', as: 'delete_admin'
  resources :admin_sessions, only: [:new, :create, :destroy]
  get 'admin_login', to: 'admin_sessions#new', as: 'admin_login'
  get 'admin_logout', to: 'admin_sessions#destroy', as: 'admin_logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_secure_password
    has_many :tickets, dependent: :destroy
    has_many :reviews, dependent: :destroy
    validates :email, presence: true, uniqueness: true
    validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    validates :password, presence: true, on: [new, create]
    validates :credit_number, numericality: { only_numeric: true }, length: {is: 16, message: "must be 16 digits"}
    validates :phone_number, length: {is: 10}
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_passenger, only: %i[ show edit update destroy ]

  # GET /passengers or /passengers.json
  def index
    if admin_user and params[:search_by_train_number].present?
      @passengers = Passenger.joins(tickets: :train).where(trains: { train_number: params[:search_by_train_number] }).where(id: Passenger.select('DISTINCT id'))
      @passengers = @passengers.distinct { |passenger| passenger.id }
    elsif admin_user
      @passengers = Passenger.where(is_admin: false)
    else
      redirect_to root_url
    end
  end

  # GET /passengers/1 or /passengers/1.json
  def show
    if !admin_user && current_passenger.id != @passenger.id
      redirect_to root_url
    elsif admin_user && @passenger.id == 1
      redirect_to root_url
    end  
  end

  # GET /passengers/new
  def new
    if admin_user || !logged_in?
      @passenger = Passenger.new
    else
      redirect_to root_url
    end


  end

  # GET /passengers/1/edit
  def edit
    if admin_user && @passenger.id == 1
      redirect_to root_url
    elsif !admin_user && current_passenger.id != @passenger.id
      redirect_to root_url
    end  
  end

  # POST /passengers or /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)
  
    respond_to do |format|
      if @passenger.save
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully created." }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1 or /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to passenger_url(@passenger), notice: "Passenger was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    session[:passenger_id]=nil
    @passenger.destroy
    
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Passenger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email, :password, :phone_number, :address, :credit_number)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_with(model: passenger) do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
        <% passenger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :credit_number %>
    <%= form.text_field :credit_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>ID</th>

      <th>Email</th>

      <th>Phone number</th>
      <th>Address</th>
      <th>Credit number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.id %></td>
        <td><%= passenger.email %></td>

        <td><%= passenger.phone_number %></td>
        <td><%= passenger.address %></td>
        <td><%= passenger.credit_number %></td>
        <td><%= link_to 'Show', passenger_path(passenger) %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= button_to 'Delete', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/passenger_search.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag passengers_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_by_train_number, params[:search_by_train_number], placeholder: "Enter train number" %>
      <%= submit_tag "search"%>
    </p>
<% end %>

<h1>Passengers</h1>

<% if admin_user && !@passengers.nil?%>


    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>ID</th>
          <th>Email</th>
          
      
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @passengers.each do |passenger| %>
          <tr>
            <td><%= passenger.name %></td>
            <td><%= passenger.id %></td>
            <td><%= passenger.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
<% end %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @passenger.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @passenger.password %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @passenger.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @passenger.address %>
</p>

<p>
  <strong>Credit number:</strong>
  <%= @passenger.credit_number %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', root_url %> |
<%= button_to 'Delete', @passenger, method: :delete, data: { confirm: 'Are you sure?' } %>